server:
  port: 5001
  
spring:
  application:
    name: USER-SERVICE
    

  datasource:
    url: jdbc:mysql://localhost:3306/task_manager
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver   
    
  jpa:
    hibernate:
      ddl-auto: update   
      